language: node_js
node_js:
  - "stable"
cache: npm
script:
  - "CI=false npm run build" #disable using CI env variable
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PersonalWeb_Token
  local_dir: build
  on:
    branch: master