language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gulp-cli gulp
script:
  - "npm run build"
after_failure:
  - "cat /home/travis/.npm/_logs/*.log"
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $PersonalWeb_Token
  local_dir: build
  on:
    branch: master